# .github/workflows/deploy.yml

name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2" # Replace with your Go version

      - name: Build Application
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/application

      - name: Zip Application
        run: zip bin/application.zip bin/application

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: websocket
          environment_name: websocket-dev
          version_label: v_${{ github.run_number }}
          region: eu-west-3
          deployment_package: bin/application.zip
